### ISSUE TITLE
onStateReceive not working

### ISSUE THREAD

**Issue by letspesl** [maticnetwork/matic-cli#118]
I have run local private network through matic-cli.
However, since there is no place to call the code below, I confirmed that the bridge contract was not deployed to bor.
https://github.com/maticnetwork/matic-cli/blob/master/src/setup/ganache/index.js#L143

So I directly executed ganache-deployment-bor.sh and ganache-deployment-sync.sh and got contractAddresses.json for child part.

However, the current bridge does not operate normally.
When I run DepositEther, the lastStateId is incremented by executing the commitState of the Child at the Root, but the onStateReceive of the ChildChainToken is not called.
How can I solve this?

**Comment by marcello33** [comment]
Hi @letspesl 
Thanks for your report
What do you mean by "there is no place to call the code"?
That function is imported here https://github.com/maticnetwork/matic-cli/blob/master/src/setup/ganache/index.js#L12 from the `remote-worker` so should be available for you to use.

**Comment by letspesl** [comment]
Sorry. I didn't know the function. I tried it and get addresses well.
But, still can't deposit ETH by using above plasma bridge.
So, I did deploy pos-portal contracts together and test it completed.
Thank you.
