### ISSUE TITLE
error-"Get \ "http: //heimdall0:1317/bor/span/1\": dial tcp 172.20.1.4:1317: connect: connection refused"

### ISSUE THREAD

**Issue by niekaixuan** [maticnetwork/matic-cli#206]
I setup my private matic network following the tutorial, all the command was successfully executed, however it was stuck in connection refused error in bor.log
<img width="1401" alt="errorlog" src="https://github.com/maticnetwork/matic-cli/assets/80301067/48802dea-0d4e-4628-b17d-1c242e898744">

**Comment by marcello33** [comment]
It seems like there's a connection error between bor and heimdall
How are you running the devnet? On a cloud (AWS or GCP?) or on your local system?
In case of cloud, have you properly setup the security group and VPCs?

**Comment by niekaixuan** [comment]
> It seems like there's a connection error between bor and heimdall How are you running the devnet? On a cloud (AWS or GCP?) or on your local system? In case of cloud, have you properly setup the security group and VPCs?

I solved this problem by setting user from ubunut to root in configs/devnet/docker-setup-config.yaml, such like this 
<img width="960" alt="image" src="https://github.com/maticnetwork/matic-cli/assets/80301067/efe66e4e-9c87-46b8-8698-2eb1894c72fe">
so it is an permission problem right?

**Comment by marcello33** [comment]
Thanks @niekaixuan 
Yes, maybe the machine you were using was configured with "root" as default user.
Glad you solved it for good. Closing the issue.
