### ISSUE TITLE
setup localnet error

### ISSUE THREAD

**Issue by PanosYang** [maticnetwork/matic-cli#21]
Install dependencies for matic contracts  error

 ✖ Install dependencies for matic contracts
      → > node-gyp rebuild
      Process templates
      Compile matic contracts
      Process scripts
      Deploy contracts
      Prepare contract addresses
      Load contract addresses
    Setup heimdall
    Setup genesis contracts
    Setup Bor
    Process scripts
(node:75703) UnhandledPromiseRejectionWarning: Error: Command failed: npm install
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 20.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/yangpan/localnet/code/contracts/node_modules/scrypt
gyp ERR! node -v v10.17.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yangpan/.npm/_logs/2021-06-30T09_21_08_423Z-debug.log

> scrypt@6.0.3 preinstall /Users/yangpan/localnet/code/contracts/node_modules/scrypt
> node node-scrypt-preinstall.js

> scrypt@6.0.3 install /Users/yangpan/localnet/code/contracts/node_modules/scrypt
> node-gyp rebuild

    at makeError (/usr/local/lib/node_modules/@maticnetwork/matic-cli/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/usr/local/lib/node_modules/@maticnetwork/matic-cli/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:75703) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:75703) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by climb-yang** [comment]
node v10.17.0
npm 6.11.3
os : macos big sur

**Comment by temaniarpit27** [comment]
Please use the latest tag and follow the instructions for successful usage.
Closing this for now.
Reopen if required
