### ISSUE TITLE
duplicate 'config' fold created under localnet when installing Matic CLI testnet

### ISSUE THREAD

**Issue by Thiaoouba-noaccount** [maticnetwork/matic-cli#27]
While following this instruction to setup matic-cli:
[https://github.com/maticnetwork/matic-cli](https://github.com/maticnetwork/matic-cli)

matic-cli setup localnet

would lead to an error:

return Object.assign(new Error(`${syscall} ${original.command} ENOENT`), {
                         ^

Error: spawn mkdir ENOENT
    at notFoundError (C:\Users\hchen\AppData\Roaming\npm\node_modules\@maticnetwork\matic-cli\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\hchen\AppData\Roaming\npm\node_modules\@maticnetwork\matic-cli\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\hchen\AppData\Roaming\npm\node_modules\@maticnetwork\matic-cli\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn mkdir',
  path: 'mkdir',
  spawnargs: [
    '-p',
    'C:\\Users\\hchen\\localnet\\config',
    'C:\\Users\\hchen\\localnet\\data',
    'C:\\Users\\hchen\\localnet\\config'
  ],
  stdout: '',
  stderr: 'A subdirectory or file -p already exists.\r\n' +
    'Error occurred while processing: -p.\r\n' +
    'A subdirectory or file C:\\Users\\hchen\\localnet\\config already exists.\r\n' +
    'Error occurred while processing: C:\\Users\\hchen\\localnet\\config.\r\n' +
    'A subdirectory or file C:\\Users\\hchen\\localnet\\data already exists.\r\n' +
    'Error occurred while processing: C:\\Users\\hchen\\localnet\\data.\r\n' +
    'A subdirectory or file C:\\Users\\hchen\\localnet\\config already exists.\r\n' +
    'Error occurred while processing: C:\\Users\\hchen\\localnet\\config.\r\n',
  failed: true,
  signal: null,
  cmd: 'mkdir -p C:\\Users\\hchen\\localnet\\config C:\\Users\\hchen\\localnet\\data C:\\Users\\hchen\\localnet\\config',
  timedOut: false,
  killed: false
}

This is because the script is trying to create a duplicated 'config' fold under localnet.

In this file: 
matic-cli\src\setup\config.js

in line 119:

 await execa('mkdir', ['-p', config.configDir, config.dataDir, config.configDir]

We should remove one of config.configDir, so it can be fixed.

**Comment by temaniarpit27** [comment]
Please use the latest tag and follow the instructions for successful usage.
Closing this for now.
Reopen if required
